# Generated by Django 5.2 on 2026-01-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ET_app", "0002_expense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="descroption",
            new_name="description",
        ),
    ]
